name: nix-buildkite
description: Generates a Buildkite pipeline from a Nix expression
author: https://github.com/circuithub
requirements: []
configuration:
  properties:
    file:
      type: string
    post-build-hook:
      type: string
    skip-already-built:
      type: string
  required:
    - file
  not:
    required:
      - post-build-hook
      - skip-already-built
  additionalProperties: false
