#!/usr/bin/env bash
set -euo pipefail

NIX_FILE="$BUILDKITE_PLUGIN_NIX_BUILDKITE_FILE"

echo "--- :nixos: Running nix-buildkite"
nix-build -E '(import "${ builtins.fetchGit { url = git://github.com/circuithub/nix-buildkite-buildkite-plugin; } }/jobs.nix").nix-buildkite' -o nix-buildkite
PIPELINE=$( NIX_PATH="$BUILDKITE_PLUGIN_NIX_BUILDKITE_NIX_PATH" ./nix-buildkite/bin/nix-buildkite "$NIX_FILE" )
rm nix-buildkite

echo "--- :pipeline: Uploading pipeline"
echo "$PIPELINE" | buildkite-agent pipeline upload
