#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

NIX_FILE="$BUILDKITE_PLUGIN_NIX_BUILDKITE_FILE"
if [[ -n "${BUILDKITE_PLUGIN_NIX_BUILDKITE_POST_BUILD_HOOK:-}" ]]; then
    export POST_BUILD_HOOK="$BUILDKITE_PLUGIN_NIX_BUILDKITE_POST_BUILD_HOOK"
fi

echo "--- :nixos: Running nix-buildkite"
nix-build -E "(import $DIR/../jobs.nix).nix-buildkite" -o nix-buildkite
PIPELINE=$( ./nix-buildkite/bin/nix-buildkite "$NIX_FILE" )
rm nix-buildkite

echo "--- :pipeline: Uploading pipeline"
echo "$PIPELINE" | buildkite-agent pipeline upload
